# Generated by Django 5.1.5 on 2025-01-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField()),
            ],
        ),
    ]
