# Generated by Django 5.1.5 on 2025-01-23 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0002_cv_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
