# Generated by Django 5.1.5 on 2025-01-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0002_jobdescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVJobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("job_description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="JobDescription",
        ),
        migrations.RemoveField(
            model_name="cvheaderinfo",
            name="user",
        ),
    ]
