# Generated by Django 5.1.5 on 2025-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0004_cveducation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
            ],
        ),
    ]
