# Generated by Django 5.1.5 on 2025-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0005_cvproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CVLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=255)),
            ],
        ),
    ]
