# Generated by Django 5.1.5 on 2025-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0006_cvcertification_cvlanguage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVHardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hard_skill", models.CharField(max_length=255)),
            ],
        ),
    ]
