# Generated by Django 5.1.5 on 2025-01-22 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0008_cv_delete_cvname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="user",
        ),
        migrations.AddField(
            model_name="cv",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
