# Generated by Django 5.1.5 on 2025-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0009_remove_cv_user_cv_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cv",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
