# Generated by Django 5.1.5 on 2025-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsubmit", "0010_alter_cv_data_alter_cv_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRecruitmentDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
